export type Organ = 'auto' | 'leaf' | 'flower' | 'fruit' | 'bark';

export interface PreparedImage {
  /** file:// JPEG, long edge 1280, q0.8 — the image sent to Pl@ntNet. */
  uri: string;
  /** 768px q0.7 render sent to the VLM, base64 (no data URI) — used directly by enrich(). */
  vlmBase64: string;
  organ: Organ;
  width: number;
  height: number;
}

export type PrepareOutcome =
  | { kind: 'ready'; image: PreparedImage }
  | { kind: 'blurry'; variance: number; threshold: number };

// --- Phase 3: identification pipeline ---

export type ConfidenceBand = 'high' | 'medium' | 'low';
export type VisualAgreement = 'high' | 'medium' | 'low';

export interface Candidate {
  latin: string;
  commonNames: string[];
  score: number;
  gbifId: string | null;
}

export interface Care {
  water: string;
  light: string;
  soil: string;
}

export interface Enrichment {
  isPlant: boolean;
  /** -1 = none of the candidates fit, the VLM is giving its own guess (ownGuessLatin is set). */
  bestMatchIndex: number;
  /** Set when bestMatchIndex === -1; the VLM's own Latin guess, independent of Pl@ntNet's candidates. */
  ownGuessLatin: string | null;
  visualAgreement: VisualAgreement;
  speciesCommonTr: string;
  care: Care | null;
  toxicToPets: boolean | null;
  toxicityNote: string | null;
  stickerTraits: string;
}

export interface IdentifiedPlant {
  /** The id of the row in the discoveries table — generated by pipeline.ts when persisting. */
  id: string;
  speciesLatin: string;
  speciesCommonTr: string | null;
  photoUri: string;
  confidence: number;
  confidenceBand: ConfidenceBand;
  bandDowngraded: boolean;
  /** Pl@ntNet's score was very low (<5%), the species came from the VLM's own guess — no Pl@ntNet confirmation. */
  viaVlmFallback: boolean;
  /** This species was already in the collection — informational only, never blocks the record. */
  isDuplicate: boolean;
  care: Care | null;
  toxicToPets: boolean | null;
  toxicityNote: string | null;
  alternatives: Candidate[];
  stickerTraits: string | null;
}

/**
 * The pipeline's REAL stages. Shown to the user as-is — not a fabricated
 * progress bar, but an honest reflection of where the pipeline actually is.
 * In a consumer scanner app it's critical that wait time feels like "it's
 * working," but showing fake stages would be misleading the user.
 */
export type IdentifyStage =
  | 'preparing'
  | 'classifying'
  | 'verifying'
  | 'adjudicating'
  | 'saving';

/** Deliberately carries no species name — this is what guarantees it stays hidden at low confidence. */
export interface SecondPhotoSession {
  images: PreparedImage[];
  attempt: 1;
}

export type IdentifyOutcome =
  | { kind: 'identified'; plant: IdentifiedPlant }
  | { kind: 'needs-second-photo'; session: SecondPhotoSession }
  /** Still low confidence after two attempts — the species name is NEVER shown, and the loop doesn't repeat. */
  | { kind: 'low-confidence-exhausted' }
  | { kind: 'not-a-plant' }
  | { kind: 'blurry'; variance: number; threshold: number }
  | { kind: 'error'; error: import('@/errors/AppError').AppError };
